# Generated by Django 5.0.6 on 2024-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('OTP_VERIFICATION', 'OTP Verification'), ('REGISTRATION', 'Registration'), ('NOTIFICATION', 'Notification'), ('WELCOME', 'Welcome')], db_index=True, default='NOTIFICATION', max_length=255),
        ),
    ]
