# Generated by Django 5.0.6 on 2025-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('OTP_VERIFICATION', 'OTP Verification'), ('REGISTRATION', 'Registration'), ('NOTIFICATION', 'Notification'), ('WELCOME', 'Welcome'), ('LETTER', 'Letter')], db_index=True, default='NOTIFICATION', max_length=255),
        ),
    ]
