# Generated by Django 5.0.6 on 2025-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_jobtitle_titer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='titer',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='titer_am',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titer (Amharic)'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='titer_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titer (English)'),
        ),
    ]
